### ISSUE TITLE
Unable to install (error Couldn't find package "surrealdb.node-win32-arm64-msvc@0.2.0" required by "surrealdb.node" on the "npm" registry.)

### ISSUE THREAD

**Issue by CanRau** [surrealdb/surrealdb.node#14]
`yarn add surrealdb.node` results in the following error

```
error Couldn't find package "surrealdb.node-win32-arm64-msvc@0.2.0" required by "surrealdb.node" on the "npm" registry.
```

I'm on macOS Big Sur (11.7.10) and unfortunately can't upgrade due to 3rd party ssd 🥲

Anything I can do? I wan't to embed ideally via file (I guess RocksDB) and potentially memory

**Comment by CanRau** [comment]
Any chance someone could help me figure this out? 😇

**Comment by CanRau** [comment]
Got it working 🥳 

1. Clone into yarn workspace
2. `yarn install` within `surrealdb.node` dir
3. changed `Cargo.toml` to
```toml
[package]
name = "surrealdb_node"
version = "0.4.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
dmp = "0.2.0"
napi = { version = "2", features = ["async", "serde-json"] }
napi-derive = "2"
serde = "1.0.188"
serde_json = "1.0.105"
surrealdb = { version = "1.0.0", features = ["kv-mem", "kv-rocksdb"] }

[build-dependencies]
napi-build = "2.0.1"

[features]
rocksdb = ["surrealdb/kv-rocksdb"]

[profile.release]
lto = true

# [target.x86_64-pc-windows-msvc.dependencies]
# surrealdb = { version = "1.0.0", features = ["kv-mem", "kv-rocksdb"] }
# [target.x86_64-unknown-linux-gnu.dependencies]
# surrealdb = { version = "1.0.0", features = ["kv-mem", "kv-rocksdb"] }
# [target.aarch64-linux-android.dependencies]
# surrealdb = { version = "1.0.0", features = ["kv-mem", "kv-rocksdb"] }
# [target.armv7-linux-androideabi.dependencies]
# surrealdb = { version = "1.0.0", features = ["kv-mem", "kv-rocksdb"] }
[target.aarch64-apple-darwin.dependencies]
surrealdb = { version = "1.0.0", features = ["kv-mem", "kv-rocksdb"] }
```
4. `yarn build` in `surrealdb.node` dir
5. add `"surrealdb.node": "0.4.0"` to main project's `package.json`
6. `yarn install` in project root
7. `yarn dev` 🚀
